# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
  deploy:  
    runs-on: ubuntu-latest
    steps:
      - name: SSH Execute Commands
      # You may pin to the exact commit or the version.
      # uses: JimCronqvist/action-ssh@d95a7435b565a2fedb9bf4100cdeb3342aa3cf16
        uses: JimCronqvist/action-ssh@1.0.0
        with:
          # Command(s) to execute on the remote server.
          command: sh /root/test/start.sh
          # Hostname or IP address of the remote server(s). Separate multiple servers with a blank space. Example: 'user@mydomain.com:22 user@otherdomain.com:2222'
          hosts: 182.160.11.117
          # The private key (id_rsa) content for authenticating to the SSH server(s). Recommended to store it as a GitHub Secret.
          privateKey: ${{ ljh_pk }}
          # Used to view all environment variables in the logs, please note that this could expose sensitive data.
          debug:  optional
